# Generated by Django 5.2 on 2025-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='day_notes',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hours',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timesheetdetail',
            unique_together={('timesheet', 'day')},
        ),
    ]
