# Generated by Django 5.2 on 2025-05-02 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_employeeprofile_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['-created_at', 'employee_id']},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('employee_profile', 'Employee Profile'), ('customer', 'Customer'), ('project', 'Project'), ('timesheet', 'Timesheet')], max_length=20)),
                ('record_uuid', models.UUIDField(db_index=True)),
                ('field_type', models.CharField(choices=[('user_details', 'User Details'), ('bank_details', 'Bank Details'), ('rate', 'Rate'), ('status', 'Status'), ('other', 'Other')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['record_type', 'record_uuid'], name='timesheets__record__9e41b3_idx'), models.Index(fields=['field_type'], name='timesheets__field_t_933e88_idx'), models.Index(fields=['changed_at'], name='timesheets__changed_d17a20_idx')],
            },
        ),
    ]
