# Generated by Django 5.2 on 2025-05-02 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_employeeprofile_options_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='daily_rate_at_submission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='fixed_price_at_submission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hourly_rate_at_submission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='retainer_amount_at_submission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('rate_type', models.CharField(choices=[('employee_hourly', 'Employee Hourly Rate'), ('project_hourly', 'Project Hourly Rate'), ('project_daily', 'Project Daily Rate'), ('project_fixed', 'Project Fixed Rate'), ('project_retainer', 'Project Retainer Rate')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rate_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='timesheets.employeeprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='timesheets.project')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['rate_type', 'effective_from'], name='timesheets__rate_ty_ed5094_idx'), models.Index(fields=['employee', 'effective_from'], name='timesheets__employe_190c5d_idx'), models.Index(fields=['project', 'effective_from'], name='timesheets__project_0cbbc7_idx')],
            },
        ),
    ]
