# Generated by Django 5.2 on 2025-05-02 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timesheet_daily_rate_at_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
