# Generated by Django 5.2 on 2025-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_timesheetdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='sent_for_payment_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
